version: '1.0.{build}'
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"
      PyQT: "https://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.4/PyQt4-4.11.4-gpl-Py2.7-Qt4.8.7-x32.exe"

install:
  - pip install -U PyInstaller

before_build:
  - ps: Start-FileDownload $env:PyQT -FileName .\pyqt4_install.exe
  - ps: .\pyqt4_install.exe /S

build_script:
  - python -m PyInstaller -i DHLR.ico -w DHLR.pyw

after_build:
  - ps: cp DHLR.* dist\DHLR\
  - ps: cd dist\
  - ps: 7z a ..\DHLR.zip DHLR\*

artifacts:
  - path: DHLR.zip
    name: DHLR

deploy:
  release: DHLR-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: DHLR.zip
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
