version: '1.0.{build}'
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  - "%PYTHON%\\python -m pip install -U PyInstaller PyQt5"

build_script:
  - "%PYTHON%\\python -m PyInstaller -F -i DHLR.ico -w DHLR.pyw"

after_build:
  - ps: rm DHLR.spec
  - ps: cp DHLR.* dist\
  - ps: cd dist\
  - ps: 7z a ..\DHLR.zip *

artifacts:
  - path: DHLR.zip
    name: DHLR

deploy:
  release: DHLR-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: DHLR.zip
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
