version: '1.0.{build}'
skip_tags: true

environment:
  matrix:
    - PYTHON: "C:\Python38"
      PYTHON_ARCH: "32"

install:
  - pip install -U PyInstaller PyQt5

build_script:
  - python -m PyInstaller -i DHLR.ico -w DHLR.pyw

after_build:
  - ps: cp DHLR.* dist\DHLR\
  - ps: cd dist\
  - ps: 7z a ..\DHLR.zip DHLR\*

artifacts:
  - path: DHLR.zip
    name: DHLR

deploy:
  release: DHLR-v$(appveyor_build_version)
  description: ''
  provider: GitHub
  auth_token:
    secure: x2VCjhjls6MUIYqj+WN0D5Db4HA3hTIep++8jGWbSQtnGcPMfzj5gWW39ZNg1z/5
  artifact: DHLR.zip
  force_update: true
  draft: false
  prerelease: false
  appveyor_repo_tag: false
